<?php

/**
 * ======================================================================
 * LICENSE: This file is subject to the terms and conditions defined in *
 * file 'license.txt', which is part of this source code package.       *
 * ======================================================================
 */
?>
<div class="feature-content-container" id="capability_content">
    <table id="capability_list">
        <thead>
            <tr>
                <th>Capability ID</th>
                <th>Checked</th>
                <th width="35%"><?php echo __('Categoria', 'aam'); ?></th>
                <th width="50%"><?php echo __('Capacidad', 'aam'); ?></th>
                <th><?php echo __('Control', 'aam'); ?></th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

    <div id="filter_capability_dialog" class="aam-dialog" title="<?php echo __('Filtrar Lista de Capacidades', 'aam'); ?>">
        <table id="capability_group_list">
            <thead>
                <tr>
                    <th><?php echo __('Nombre de Grupo', 'aam'); ?></th>
                    <th><?php echo __('Seleccionar', 'aam'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->getGroupList() as $group) { ?>
                    <tr>
                        <td><?php echo $group; ?></td>
                        <td>
                            <div class="aam-list-row-actions">
                                <a href="#" class="aam-icon aam-icon-small aam-icon-select"><span></span></a>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>

    <div id="copy_role_dialog" class="aam-dialog" title="<?php echo __('Heredar Capacidades', 'aam'); ?>">
        <table id="copy_role_list">
            <thead>
                <tr>
                    <th>Role ID</th>
                    <th>User Count</th>
                    <th width="80%"><?php echo __('Nombre Rol', 'aam'); ?></th>
                    <th><?php echo __('Accion', 'aam'); ?></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
        <div class="aam-metabox-loader"></div>
    </div>

    <div id="capability_form_dialog" class="aam-dialog" title="<?php echo __('Agregar Nueva Capacidad', 'aam'); ?>">
        <table class="dataTable">
            <tbody>
                <tr>
                    <th class="aam-align-right"><?php echo __('Nombre Capabicidad ', 'aam'); ?><span class="aam-asterix">*</span>:</th>
                    <td><input type="text" id="capability_name" class="aam-input" /></td>
                </tr>
                <tr>
                    <th class="aam-align-right"><?php echo __('Mantener sin filtrar', 'aam'); ?>:</th>
                    <td>
                        <input type="checkbox" id="capability_unfiltered" />
                        <label for="capability_unfiltered"><span></span></label>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="aam-metabox-loader"></div>
    </div>

    <div id="delete_capability" class="aam-dialog" title="<?php echo __('Borrar Capacidad', 'aam'); ?>">
        <p class="dialog-content"></p>
    </div>
</div>